version: "3.7"
services:
  report:
    build: .
    restart: always
    environment:
       SPRING_PROFILES_ACTIVE: prod
       DB_URL: "jdbc:postgresql://greedobank_report-db:5432/greedobank?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true"
       DB_USER: okukurik
       DB_PASSWORD: 12345
       SERVICE_URL: "http://docker.for.mac.localhost:8082/api/v1/users"
       MAIL_HOST: "smtp.gmail.com"
       MAIL_USER: “sendermailreportproject@gmail.com”
       MAIL_PASSWORD: “fphkglicxokgqeeq”
    ports:
      - "8080:8080"
    depends_on:
      - greedobank_report-db

  greedobank_report-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: 'greedobank'
      DB_USER: okukurik
      DB_PASSWORD: 12345
