version: "3.7"
services:
  report:
    build: .
    restart: always
    environment:
      DB_URL: jdbc:postgresql://docker.for.mac.localhost:5432/greedobank?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      DB_USER: okukurik
      DB_PASSWORD: 12345
    ports:
      - "8080:8080"
    depends_on:
      - greedobank_report-db

  greedobank_report-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: greedobank
      DB_USER: okukurik
      DB_PASSWORD: 12345
